# Generated by Django 5.1.7 on 2025-03-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_cancellation_reason_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ID de Pagamento')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('pix', 'PIX')], max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência Externa')),
                ('payment_data', models.JSONField(blank=True, null=True, verbose_name='Dados do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
