# Generated by Django 5.1.7 on 2025-04-03 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_options_alter_cartitem_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_data',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='mercado_pago_id',
            field=models.CharField(default='mp-id-placeholder', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Aprovado'), ('PENDING', 'Pendente'), ('IN_PROCESS', 'Em Processamento'), ('REJECTED', 'Rejeitado'), ('REFUNDED', 'Reembolsado'), ('CANCELLED', 'Cancelado'), ('UNKNOWN', 'Desconhecido')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
